package homework.Emanuel.Selenium1_HomeWork;


import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class LocatorExercisesPt2_Selenium1 {

    private static final String COD_UNIC_QA = "https://demoqa.com/elements";


    public static void main(String[] args) throws InterruptedException {

        WebDriverManager.chromedriver().setup();
        WebDriver start = new ChromeDriver();
        start.manage().window().maximize();
        start.get(COD_UNIC_QA);
        Thread.sleep(500);
        WebElement element = start.findElement(By.xpath("//li[contains(.,'Text Box')]"));
        element.click();
        Thread.sleep(500);
        WebElement element1 = start.findElement(By.id("userName"));
        element1.sendKeys("Istrate Emanuel");
        Thread.sleep(500);
        WebElement element2 = start.findElement(By.id("userEmail"));
        element2.sendKeys("marin.mm758@gmail.com");
        Thread.sleep(500);
        WebElement element3 = start.findElement(By.id("currentAddress"));
        element3.sendKeys("->Tara: Romania");
        element3.sendKeys("->Judet: Dambovita");
        element3.sendKeys("->Oras: Targoviste");
        element3.sendKeys("->Localitate: Draomiresti");
        element3.sendKeys("->Strada: Ciocanesti");
        element3.sendKeys("->Numar: 123");
        Thread.sleep(500);
        WebElement element4 = start.findElement(By.id("permanentAddress"));
        element4.sendKeys("->Tara: Romania");
        element4.sendKeys("->Judet: Dambovita");
        element4.sendKeys("->Oras: Targoviste");
        element4.sendKeys("->Localitate: Draomiresti");
        element4.sendKeys("->Strada: Ciocanesti");
        element4.sendKeys("->Numar: 123");
        Thread.sleep(500);
        start.findElement(By.id("submit")).click();
        Thread.sleep(500);
        WebElement element5 = start.findElement(By.xpath("//span[.='Check Box']"));
        element5.click();
        Thread.sleep(500);
        WebElement element6 = start.findElement(By.xpath("//button[contains(@aria-label,'Expand all')]"));
        element6.click();
        Thread.sleep(500);
        WebElement element7 = start.findElement(By.xpath("//span[text()='Private']"));
        element7.click();
        Thread.sleep(500);
        WebElement element8 = start.findElement(By.xpath("(//button[@aria-label='Toggle'])[1]"));
        element8.click();
        Thread.sleep(1000);
        WebElement element9 = start.findElement(By.xpath("//span[.='Radio Button']"));
        element9.click();
        Thread.sleep(1000);
        WebElement element10 = start.findElement(By.xpath("//label[contains(.,'Yes')]"));
        element10.click();
        Thread.sleep(800);
        WebElement element11 = start.findElement(By.xpath("//li[contains(.,'Web Tables')]"));
        element11.click();
        Thread.sleep(800);
        WebElement element12 = start.findElement(By.id("addNewRecordButton"));
        element12.click();
        Thread.sleep(700);
        WebElement firstName = start.findElement(By.id("firstName"));
        firstName.sendKeys("Istrate");
        Thread.sleep(300);
        WebElement lastName = start.findElement(By.id("lastName"));
        lastName.sendKeys("Emanuel");
        Thread.sleep(300);
        WebElement userEmail = start.findElement(By.id("userEmail"));
        userEmail.sendKeys("marin.mm758@gmail.com");
        Thread.sleep(300);
        WebElement age = start.findElement(By.id("age"));
        age.sendKeys("24");
        Thread.sleep(300);
        WebElement salary = start.findElement(By.id("salary"));
        salary.sendKeys("80000");
        Thread.sleep(300);
        WebElement department = start.findElement(By.id("department"));
        department.sendKeys("Director");
        Thread.sleep(800);
        WebElement submit = start.findElement(By.id("submit"));
        submit.click();

        WebElement element13 = start.findElement(By.id("addNewRecordButton"));
        element13.click();
        Thread.sleep(300);
        WebElement firstName1 = start.findElement(By.id("firstName"));
        firstName1.sendKeys("Elizabet");
        Thread.sleep(300);
        WebElement lastName1 = start.findElement(By.id("lastName"));
        lastName1.sendKeys("Nelis");
        Thread.sleep(300);
        WebElement userEmail1 = start.findElement(By.id("userEmail"));
        userEmail1.sendKeys("Elizabet.mm778@gmail.com");
        Thread.sleep(300);
        WebElement age1 = start.findElement(By.id("age"));
        age1.sendKeys("23");
        Thread.sleep(300);
        WebElement salary1 = start.findElement(By.id("salary"));
        salary1.sendKeys("30000");
        Thread.sleep(300);
        WebElement department1 = start.findElement(By.id("department"));
        department1.sendKeys("Secretara");
        Thread.sleep(600);
        WebElement submit1 = start.findElement(By.id("submit"));
        submit1.click();

        WebElement element14 = start.findElement(By.id("addNewRecordButton"));
        element14.click();
        Thread.sleep(300);
        WebElement firstName2 = start.findElement(By.id("firstName"));
        firstName2.sendKeys("Gofran");
        Thread.sleep(300);
        WebElement lastName2 = start.findElement(By.id("lastName"));
        lastName2.sendKeys("Medin");
        Thread.sleep(300);
        WebElement userEmail2 = start.findElement(By.id("userEmail"));
        userEmail2.sendKeys("Gofran.md024@gmail.com");
        Thread.sleep(300);
        WebElement age2 = start.findElement(By.id("age"));
        age2.sendKeys("22");
        Thread.sleep(300);
        WebElement salary2 = start.findElement(By.id("salary"));
        salary2.sendKeys("20000");
        Thread.sleep(300);
        WebElement department2 = start.findElement(By.id("department"));
        department2.sendKeys("Directoare");
        Thread.sleep(600);
        WebElement submit2 = start.findElement(By.id("submit"));
        submit2.click();
        start.findElement(By.id("edit-record-1")).click();
        Thread.sleep(600);
        WebElement submit3 = start.findElement(By.id("submit"));
        submit3.click();
        Thread.sleep(400);
        WebElement delete = start.findElement(By.id("delete-record-1"));
        delete.click();
        Thread.sleep(400);
        WebElement delete1 = start.findElement(By.id("delete-record-2"));
        delete1.click();
        Thread.sleep(400);
        WebElement delete2 = start.findElement(By.id("delete-record-3"));
        delete2.click();
        Thread.sleep(300);
        WebElement searchBox = start.findElement(By.id("searchBox"));
        searchBox.sendKeys("Emanu");
        Thread.sleep(1000);
        searchBox.clear();
        Thread.sleep(300);
        WebElement searchBox1 = start.findElement(By.id("searchBox"));
        searchBox1.sendKeys("Eliza");
        Thread.sleep(1000);
        searchBox.clear();
        Thread.sleep(300);
        WebElement searchBox2 = start.findElement(By.id("searchBox"));
        searchBox2.sendKeys("Gofr");
        Thread.sleep(1000);
        searchBox.clear();
        Thread.sleep(300);
        WebElement element16 = start.findElement(By.xpath("//span[contains(@class,'select-wrap -pageSizeOptions')]"));
        element16.click();
        WebElement element15 = start.findElement(By.cssSelector("select[aria-label='rows per page']"));
        Select selector = new Select(element15);
        selector.selectByContainsVisibleText("25");
        Thread.sleep(300);
        WebElement element17 = start.findElement(By.xpath("//li[contains(.,'Buttons')]"));
        element17.click();
//        WebElement doubleClickMessage = start.findElement(By.xpath("//button[.='Double Click Me']"));
//        doubleClickMessage.click();
//        WebElement doubleClickMessage1 = start.findElement(By.xpath("//button[.='Double Click Me']"));
//        doubleClickMessage1.

//        WebElement rightClickBtn = start.findElement(By.id("rightClickBtn"));
//        rightClickBtn.submit();
        start.findElement(By.xpath("//button[.='Click Me']")).click();
        Thread.sleep(300);
        WebElement element18 = start.findElement(By.xpath("//li[.='Links']"));
        element18.click();
        WebElement created = start.findElement(By.id("created"));
        created.click();
        Thread.sleep(300);
        WebElement element19 = start.findElement(By.id("no-content"));
        element19.click();
        Thread.sleep(300);
        start.findElement(By.id("moved")).click();
        Thread.sleep(300);
        start.findElement(By.id("bad-request")).click();
        Thread.sleep(300);
        start.findElement(By.id("unauthorized")).click();
        Thread.sleep(300);
        start.findElement(By.id("forbidden")).click();
        Thread.sleep(300);
        start.findElement(By.id("invalid-url")).click();
        Thread.sleep(300);
        WebElement simpleLink = start.findElement(By.id("simpleLink"));
        simpleLink.click();
    }
}
